general {
    # Lock screen with Hyprlock
    lock_cmd = pidof hyprlock || hyprlock
    # Run before system suspend (can also lock here just in case)
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
}

# Screen off after x minutes of inactivity
listener {
    timeout = 60
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock after Y minutes of inactivity  
listener {
    timeout = 300
    on-timeout = 
    # Custom command to turn screen on (if off) and lock
    on-timeout = bash -c 'hyprctl dispatch dpms on; sleep 0.1; hyprlock'
    on-resume = 
}
