general {
    lock_cmd               = pidof hyprlock || hyprlock
    before_sleep_cmd       = loginctl lock-session
    after_sleep_cmd        = hyprctl dispatch dpms on
    ignore_dbus_inhibit    = false
    ignore_systemd_inhibit = false
}

# Dim the display after 2 minutes of inactivity.
listener {
    timeout    = 120
    on-timeout = brightnessctl -s set 40%
    on-resume  = brightnessctl -r
}

# Lock the session after 5 minutes.
listener {
    timeout    = 300
    on-timeout = loginctl lock-session
}

# Turn the display off after 6 minutes.
listener {
    timeout    = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# Suspend system after 10 minutes.
listener {
    timeout    = 600
    on-timeout = systemctl suspend
}
