# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        14.0

confirm_os_window_close 0

scrollback_lines 1000000

# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
